# Pandas

# it's important it consume 80% time

In [ ]:
!pip install pandas

:

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

# Creating Series

In [ ]:
import numpy as np

In [ ]:
ar1 = np.random.randint(30,100,10)
print(pd.Series(ar1))

0    91
1    91
2    81
3    73
4    45
5    85
6    43
7    80
8    78
9    66
dtype: int32

In [ ]:
arr = np.random.randint(30,100,15).reshape(3,5)
arr

array([[33, 89, 69, 35, 84],
       [32, 71, 54, 67, 79],
       [66, 62, 72, 61, 46]], dtype=int32)

In [ ]:
s = pd.DataFrame(arr,index = ["A","B","C"], columns = ["Ma","Sc","HI","Env","En"])
print(s)

   Ma  Sc  HI  Env  En
A  33  89  69   35  84
B  32  71  54   67  79
C  66  62  72   61  46

In [ ]:
s

   Ma  Sc  HI  Env  En
A  33  89  69   35  84
B  32  71  54   67  79
C  66  62  72   61  46

In [ ]:
s.head(1)

   Ma  Sc  HI  Env  En
A  33  89  69   35  84

In [ ]:
s.head(2)

   Ma  Sc  HI  Env  En
A  33  89  69   35  84
B  32  71  54   67  79

In [ ]:
s.tail(1)

   Ma  Sc  HI  Env  En
C  66  62  72   61  46

In [ ]:
s.sample(2)

   Ma  Sc  HI  Env  En
B  32  71  54   67  79
C  66  62  72   61  46

In [ ]:
s

   Ma  Sc  HI  Env  En
A  33  89  69   35  84
B  32  71  54   67  79
C  66  62  72   61  46

In [ ]:
print(s.loc["C","HI"])

72

In [ ]:
s.loc["C"]

Ma     66
Sc     62
HI     72
Env    61
En     46
Name: C, dtype: int32

In [ ]:
print(s)

   Ma  Sc  HI  Env  En
A  33  89  69   35  84
B  32  71  54   67  79
C  66  62  72   61  46