In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\vaibh\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vaibh\appdata\roaming\python\python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vaibh\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vaibh\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vaibh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vaibh\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.3

In [4]:
import numpy as np

In [5]:
arr = np.random.randint(30,100,20).reshape(4,5)
arr

array([[93, 97, 41, 64, 56],
       [85, 71, 61, 35, 44],
       [77, 88, 36, 85, 96],
       [31, 34, 32, 44, 46]], dtype=int32)

In [6]:
t = pd.DataFrame(arr,index = ["A","B","C","D"], columns = ["Ma","Sc","HI","Env","En"])
print(t)

   Ma  Sc  HI  Env  En
A  93  97  41   64  56
B  85  71  61   35  44
C  77  88  36   85  96
D  31  34  32   44  46

In [13]:
t.head(2)

   Ma  Sc  HI  Env  En
A  68  96  89   60  49
B  64  79  75   73  82

In [15]:
t.loc["A"]

Ma     68
Sc     96
HI     89
Env    60
En     49
Name: A, dtype: int32

In [10]:
print(int(t.loc["A","HI"]))

41

In [12]:
t.loc["A":"C"]

   Ma  Sc  HI  Env  En
A  93  97  41   64  56
B  85  71  61   35  44
C  77  88  36   85  96

In [18]:
t.loc["A":"D","Ma"]

A    93
B    85
C    77
D    31
Name: Ma, dtype: int32

# iloc

In [22]:
a1 = np.random.randint(40,100,35).reshape(7,5)
a1

array([[95, 52, 89, 63, 66],
       [58, 84, 49, 64, 56],
       [87, 71, 83, 60, 92],
       [86, 62, 70, 52, 64],
       [46, 40, 71, 95, 64],
       [94, 97, 75, 63, 59],
       [70, 70, 81, 90, 85]], dtype=int32)

In [23]:
t1 = pd.DataFrame(a1,index = ["0","1","2","3","4","5","6"], columns = ["a","b","c","d","v"])
print(t1)

    a   b   c   d   v
0  95  52  89  63  66
1  58  84  49  64  56
2  87  71  83  60  92
3  86  62  70  52  64
4  46  40  71  95  64
5  94  97  75  63  59
6  70  70  81  90  85

In [27]:
t1.iloc[2:7,[2,3]]

    c   d
2  83  60
3  70  52
4  71  95
5  75  63
6  81  90

In [41]:
t1

    a   b   c   d   v
0  77  70  81  85  75
1  72  90  47  99  77
2  44  46  91  45  46
3  40  59  48  94  95
4  40  59  40  53  99
5  53  53  53  93  46
6  62  90  85  46  79

In [19]:
t1.iloc[0:6,[1,3]]

    b   d
0  96  85
1  76  97
2  87  53
3  54  72
4  45  65
5  67  88

# appling logical operation in loc

In [39]:
a2 = np.random.randint(40,100,50).reshape(10,5)
a2

array([[62, 54, 45, 94, 60],
       [79, 72, 74, 84, 52],
       [60, 93, 64, 70, 75],
       [81, 71, 65, 59, 98],
       [70, 55, 83, 70, 43],
       [52, 65, 89, 46, 48],
       [70, 55, 79, 75, 96],
       [74, 84, 88, 89, 46],
       [93, 56, 46, 70, 97],
       [58, 97, 62, 67, 43]], dtype=int32)

In [40]:
t2 = pd.DataFrame(a2,index = [0,1,2,3,4,5,6,7,8,9], columns = ["a","b","c","d","v"])
print(t2)

    a   b   c   d   v
0  62  54  45  94  60
1  79  72  74  84  52
2  60  93  64  70  75
3  81  71  65  59  98
4  70  55  83  70  43
5  52  65  89  46  48
6  70  55  79  75  96
7  74  84  88  89  46
8  93  56  46  70  97
9  58  97  62  67  43

In [41]:
t2

    a   b   c   d   v
0  62  54  45  94  60
1  79  72  74  84  52
2  60  93  64  70  75
3  81  71  65  59  98
4  70  55  83  70  43
5  52  65  89  46  48
6  70  55  79  75  96
7  74  84  88  89  46
8  93  56  46  70  97
9  58  97  62  67  43

In [42]:
t2.loc[t2['c'] > 70,['a','c']]

    a   c
1  79  74
4  70  83
5  52  89
6  70  79
7  74  88

In [47]:
pwd

'C:\\Users\\vaibh'

In [48]:
pwd

'C:\\Users\\vaibh'

In [49]:
pwd

'C:\\Users\\vaibh'

In [50]:
pwd

'C:\\Users\\vaibh'

In [52]:
# how to import the file in pandas

In [63]:
A = pd.read_excel("iris.xlsx")
A

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# reading the file through folders

In [21]:
df = pd.read_excel("Test_file.xlsx")
df

    ID      Name   Subjects  Marks
0  103       Sam    English     81
1  105     Sandy    Physics     70
2  101    Andrew  Chemistry     66
3  106   Michael      Maths     91
4  106    Gautam      Maths     91
5  111  Michelle    English     88

# reading the file through address

In [56]:
pd.read_excel(r"C:\Users\vaibh\OneDrive\Desktop\Test_file.xlsx")

    ID      Name   Subjects  Marks
0  103       Sam    English     81
1  105     Sandy    Physics     70
2  101    Andrew  Chemistry     66
3  106   Michael      Maths     91
4  106    Gautam      Maths     91
5  111  Michelle    English     88

# Exporting

In [22]:
df.to_excel(r"C:\Users\vaibh\OneDrive\Desktop\abcd.xlsx")

In [ ]:
# client give the data file
# data dedo
#  
#

In [61]:
df

    ID      Name   Subjects  Marks
0  103       Sam    English     81
1  105     Sandy    Physics     70
2  101    Andrew  Chemistry     66
3  106   Michael      Maths     91
4  106    Gautam      Maths     91
5  111  Michelle    English     88

In [64]:
A

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [65]:
A.head(11)

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa

In [68]:
A.sample()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
8           4.4          2.9           1.4          0.2  setosa

In [69]:
A.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [71]:
A.tail(5)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [72]:
A.index

RangeIndex(start=0, stop=150, step=1)

In [76]:
A.tail(1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
149           5.9          3.0           5.1          1.8  virginica

# 25/10/25

# Pandas roadmap 01

In [44]:
p1 = pd.read_csv("tips.csv")
p1

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [45]:
p1.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [46]:
p1.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

# renameing the names

In [47]:
p1 = p1.rename(columns={"Payer Name":"Payer_name","CC Number": "CC_Number","Payment ID":"Payment_ID"})

In [48]:
p1.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer_name,CC_Number,Payment_ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

# Statistical Description

In [49]:
# Shape use for finding rows and columns
p1.shape

(244, 11)

In [50]:
p1.describe()

       total_bill         tip        size  price_per_person     CC_Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [51]:
p1[["tip"]].head(3)

    tip
0  1.01
1  1.66
2  3.50

In [52]:
p1.iloc[:,[0,3]]

     total_bill smoker
0         16.99     No
1         10.34     No
2         21.01     No
3         23.68     No
4         24.59     No
..          ...    ...
239       29.03     No
240       27.18    Yes
241       22.67    Yes
242       17.82     No
243       18.78     No

[244 rows x 2 columns]

# Adding Calculation columns in Data

In [71]:
# Here 2 Stands for 2 values after decimal
p1["tip_Percentage"]=round(p1["tip"]/p1["total_bill"]*100,2)

In [72]:
p1

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer_name,CC_Number,Payment_ID,tip_Percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.94
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.97

# Drop use for remove the columns

In [73]:
p1.drop("tip_Percentage",axis=1,inplace=True)

In [74]:
p1

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer_name,CC_Number,Payment_ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

# taking the specific columns to index

In [53]:
p1=p1.set_index("Payment_ID")

In [55]:
p1

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer_name,CC_Number
Payment_ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [57]:
p1=p1.reset_index()

In [58]:
p1.head()

,Payment_ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer_name,CC_Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [ ]:
p1

# go to 03_pandas